#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 jvmName
  exit
 fi
java -ea -Xms2m -cp '../../../../../jars/*:../../../../../bin' -Djava.security.manager -Djava.security.policy=dcvm.policy fr.upmc.tests.multijvm.TestDistributedCVM $1 config.xml
